"""Create Repository Miner MVP persistence schema."""
from alembic import op
import sqlalchemy as sa

revision = "001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("credential_references", sa.Column("id", sa.String(36), primary_key=True), sa.Column("kind", sa.String(32), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("ciphertext", sa.Text(), nullable=False), sa.Column("key_version", sa.String(64), nullable=False), sa.Column("fingerprint", sa.String(128), nullable=False), sa.Column("compromised_at", sa.DateTime(timezone=True)), sa.Column("replaced_by_id", sa.String(36)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_rotated_at", sa.DateTime(timezone=True)))
    op.create_table("monitoring_configurations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("gitlab_base_url", sa.String(512), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("target_branch", sa.String(255), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("current_credential_id", sa.String(36), sa.ForeignKey("credential_references.id")), sa.Column("connection_validated_at", sa.DateTime(timezone=True)), sa.Column("validated_gitlab_base_url", sa.String(512)), sa.Column("validated_credential_id", sa.String(36)))
    op.create_table("mining_executions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("terminal_reason", sa.String(512)), sa.Column("commits_discovered", sa.Integer(), nullable=False), sa.Column("commits_verified", sa.Integer(), nullable=False), sa.Column("allowed_commits", sa.Integer(), nullable=False), sa.Column("unauthorized_commits", sa.Integer(), nullable=False), sa.Column("repositories_processed", sa.Integer(), nullable=False), sa.Column("repositories_failed", sa.Integer(), nullable=False))
    op.create_table("repository_selection_rules", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("kind", sa.String(16), nullable=False), sa.Column("mode", sa.String(16), nullable=False), sa.Column("external_id", sa.String(255), nullable=False), sa.UniqueConstraint("configuration_id", "kind", "external_id", name="uq_selection_scope"))
    op.create_table("allowed_users", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("original_email", sa.String(320), nullable=False), sa.Column("normalized_email", sa.String(320), nullable=False), sa.UniqueConstraint("configuration_id", "normalized_email", name="uq_allowed_email"))
    op.create_table("repository_checkpoints", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("repository_id", sa.String(255), nullable=False), sa.Column("branch", sa.String(255), nullable=False), sa.Column("baseline_sha", sa.String(255), nullable=False), sa.Column("last_processed_sha", sa.String(255), nullable=False), sa.Column("initialized_at", sa.DateTime(timezone=True), nullable=False), sa.Column("advanced_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("configuration_id", "repository_id", "branch", name="uq_checkpoint_scope"))
    op.create_table("repository_executions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("execution_id", sa.String(36), sa.ForeignKey("mining_executions.id"), nullable=False), sa.Column("repository_id", sa.String(255), nullable=False), sa.Column("branch", sa.String(255), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("observed_head", sa.String(255)), sa.Column("failure_reason", sa.String(512)), sa.UniqueConstraint("execution_id", "repository_id", "branch", name="uq_repository_execution"))
    op.create_table("commit_verifications", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("repository_id", sa.String(255), nullable=False), sa.Column("branch", sa.String(255), nullable=False), sa.Column("commit_hash", sa.String(255), nullable=False), sa.Column("author_name", sa.String(320), nullable=False), sa.Column("author_email", sa.String(320)), sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("authorization_result", sa.String(16), nullable=False), sa.Column("first_verified_execution_id", sa.String(36), sa.ForeignKey("mining_executions.id"), nullable=False), sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("configuration_id", "repository_id", "branch", "commit_hash", name="uq_commit_verification_identity"))
    op.create_table("unauthorized_commit_alerts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("execution_id", sa.String(36), sa.ForeignKey("mining_executions.id"), nullable=False), sa.Column("commit_verification_id", sa.String(36), sa.ForeignKey("commit_verifications.id"), nullable=False, unique=True), sa.Column("repository_id", sa.String(255), nullable=False), sa.Column("branch", sa.String(255), nullable=False), sa.Column("commit_hash", sa.String(255), nullable=False), sa.Column("author_name", sa.String(320), nullable=False), sa.Column("author_email", sa.String(320)), sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("websocket_tickets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("ticket_digest", sa.String(128), unique=True, nullable=False), sa.Column("operator_id", sa.String(255), nullable=False), sa.Column("execution_id", sa.String(36), sa.ForeignKey("mining_executions.id"), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("consumed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("credential_incidents", sa.Column("id", sa.String(36), primary_key=True), sa.Column("credential_id", sa.String(36), sa.ForeignKey("credential_references.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("suspected_by", sa.String(255), nullable=False), sa.Column("safe_reason", sa.String(512), nullable=False), sa.Column("suspected_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("credential_replacements", sa.Column("id", sa.String(36), primary_key=True), sa.Column("configuration_id", sa.String(36), sa.ForeignKey("monitoring_configurations.id"), nullable=False), sa.Column("previous_credential_id", sa.String(36), sa.ForeignKey("credential_references.id"), unique=True, nullable=False), sa.Column("replacement_credential_id", sa.String(36), sa.ForeignKey("credential_references.id"), nullable=False), sa.Column("reason", sa.String(32), nullable=False), sa.Column("replaced_by", sa.String(255), nullable=False), sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=False), sa.Column("incident_id", sa.String(36), sa.ForeignKey("credential_incidents.id")))


def downgrade() -> None:
    for table in ["credential_replacements", "credential_incidents", "websocket_tickets", "unauthorized_commit_alerts", "commit_verifications", "repository_executions", "repository_checkpoints", "allowed_users", "repository_selection_rules", "mining_executions", "monitoring_configurations", "credential_references"]:
        op.drop_table(table)

