import { useEffect, useState } from "react";
import { Alert, Button, Chip, FormControlLabel, Stack, Switch, TextField, Typography } from "@mui/material";
import { Configuration, getBranches, getConfiguration, getGitLabTree, saveAllowedUsers, saveSchedule, saveScope, Schedule, SelectionRule, TreeNode, updateConfiguration, updateConnection, validateConnection } from "./api";
import { CredentialIncidentPanel } from "./CredentialIncidentPanel";
import { ScopeFields } from "./ScopeFields";
import { ScheduleAndUsersFields } from "./ScheduleAndUsersFields";
import { safeErrorMessage } from "../shared/api/errors";

export function ConfigurationEditor({ configuration, onSaved, onRun }: { configuration: Configuration; onSaved: () => void; onRun: (id: string) => void }) {
  const [name, setName] = useState(configuration.name); const [url, setUrl] = useState(configuration.gitlab_base_url); const [token, setToken] = useState(""); const [enabled, setEnabled] = useState(configuration.enabled);
  const [validated, setValidated] = useState(configuration.connection_validated); const [tree, setTree] = useState<TreeNode[]>([]); const [selected, setSelected] = useState(new Set<string>()); const [branch, setBranch] = useState(configuration.target_branch ?? "QA"); const [branches, setBranches] = useState<string[]>([]);
  const [emails, setEmails] = useState(""); const [schedule, setSchedule] = useState<Schedule>({ recurrence: "daily", local_time: "09:00", timezone: configuration.timezone ?? "UTC" }); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  useEffect(() => { void getConfiguration(configuration.id).then(async (value) => { setName(value.name); setUrl(value.gitlab_base_url); setEnabled(value.enabled); setValidated(value.connection_validated); setBranch(value.target_branch ?? "QA"); setEmails((value.allowed_emails ?? []).join("\n")); if (value.schedule) setSchedule(value.schedule); const repositoryIds = (value.selections ?? []).filter((rule) => rule.mode === "include" && rule.kind === "repository").map((rule) => rule.external_id); setSelected(new Set((value.selections ?? []).filter((rule) => rule.mode === "include").map((rule) => rule.external_id))); if (value.connection_validated) { const result = await getGitLabTree(value.id); setTree(result.items); const results = await Promise.all(repositoryIds.map((id) => getBranches(value.id, id).catch(() => ({ items: [] })))); setBranches([...new Set(results.flatMap((result) => result.items))]); } }).catch((cause) => setError(safeErrorMessage(cause, "Não foi possível carregar a configuração."))); }, [configuration.id]);
  async function validate() { setBusy(true); setError(undefined); try { if (url !== configuration.gitlab_base_url || token) { await updateConnection(configuration.id, { gitlab_base_url: url, ...(token ? { gitlab_token: token } : {}) }); setToken(""); } await validateConnection(configuration.id); const result = await getGitLabTree(configuration.id); setTree(result.items); setValidated(true); setMessage("Conexão validada."); onSaved(); } catch (cause) { setValidated(false); setError(safeErrorMessage(cause, "Não foi possível validar a conexão GitLab.")); } finally { setBusy(false); } }
  async function save() { setBusy(true); setError(undefined); try { if (!name.trim() || name.trim().length > 120) throw { message: "O nome deve ter entre 1 e 120 caracteres." }; if (name.trim() !== configuration.name || enabled !== configuration.enabled || schedule.timezone !== (configuration.timezone ?? "UTC")) await updateConfiguration(configuration.id, { name: name.trim(), enabled, timezone: schedule.timezone }); const rules: SelectionRule[] = [...selected].map((external_id) => ({ kind: "repository", mode: "include", external_id })); if (validated) await saveScope(configuration.id, branch, rules); const seen = new Set<string>(); const normalized = emails.split(/[;,\n]/).map((value) => value.trim()).filter((value) => value && !seen.has(value.toLocaleLowerCase()) && Boolean(seen.add(value.toLocaleLowerCase()))); await saveAllowedUsers(configuration.id, normalized); await saveSchedule(configuration.id, schedule); setMessage("Configuração salva."); onSaved(); } catch (cause) { setError(safeErrorMessage(cause, "Não foi possível salvar a configuração.")); } finally { setBusy(false); } }
  return <Stack spacing={2}><Typography variant="h5">Configuração</Typography><Stack direction="row" spacing={1}><Chip label={enabled ? "habilitado" : "desabilitado"} /><Chip label={configuration.credential_status} color={configuration.credential_status === "active" ? "success" : "warning"} /></Stack>{message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}<TextField label="Nome" value={name} inputProps={{ maxLength: 120 }} onChange={(e) => setName(e.target.value)} /><TextField label="URL GitLab" value={url} onChange={(e) => { setUrl(e.target.value); setValidated(false); }} /><TextField label="Nova credencial" type="password" autoComplete="new-password" value={token} helperText="Deixe em branco para manter a credencial atual" onChange={(e) => { setToken(e.target.value); setValidated(false); }} /><Button variant="outlined" disabled={busy} onClick={() => void validate()}>Validar conexão</Button><ScopeFields validated={validated} tree={tree} selected={selected} branch={branch} branches={branches} onSelectedChange={(value) => { setSelected(value); const id = [...value][0]; if (id) void getBranches(configuration.id, id).then((result) => setBranches(result.items)); }} onBranchChange={setBranch} /><ScheduleAndUsersFields emails={emails} schedule={schedule} onEmailsChange={setEmails} onScheduleChange={setSchedule} /><FormControlLabel control={<Switch checked={enabled} onChange={(_, value) => setEnabled(value)} />} label="Plano habilitado" /><Stack direction={{ xs: "column", sm: "row" }} spacing={1}><Button variant="contained" disabled={busy || !validated} onClick={() => void save()}>Salvar configuração</Button><Button disabled={busy} onClick={() => onRun(configuration.id)}>Executar agora</Button></Stack><CredentialIncidentPanel configuration={configuration} onChanged={onSaved} /></Stack>;
}
